### ISSUE TITLE
Rework the unique ID generation

### ISSUE THREAD

**Issue by wilsonge** [joomla-extensions/jstats-plugin#3]
@nikosdion opinion was that the generation of the unique ID might allow the secret key to be deduced. We should rework how the unique ID is generated therefore.

**Comment by mbabker** [comment]
FWIW, this is what we're using for Mautic:

```php
hash('sha1', $config->get('secret') . 'Mautic' . $config->get('some_param_that_should_never_change'))
```

If you're aiming for something that can be regenerated, I'd append `time()` onto that too.  Long and short, avoid an MD5 hash when all is said and done.

**Comment by wilsonge** [comment]
Yah we're already currently appending the ```time()``` https://github.com/joomla-extensions/jstats-plugin/blob/master/script.php#L72 - so makes sense to keep doing that I guess
